"""Regenerate doc-names.tsv: the Arabic -> English lookup of Nama document and screen names.

Every English docs page has an Arabic mirror at the identical path under docs/ar/, so pairing
their H1 headings yields the real screen names with no guesswork. Nama's English names are often
NOT translations of the Arabic (مقايسة = "Assay", مستخلص = "Extract", حصر كميات = "Execution"),
which is exactly why this table has to be derived from the pages rather than invented.

    python tools/release-notes/gen-doc-names.py        # from the namaerp-docs root
"""
import glob, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.abspath(os.path.join(HERE, "..", "..", "docs"))
OUT = os.path.join(HERE, "doc-names.tsv")

TREES = ("modules", "platform", "admin", "integration", "getting-started")


def h1(path):
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# "):
                return line[2:].strip()
    return None


def main():
    pairs = set()
    for tree in TREES:
        for en_p in glob.glob(os.path.join(DOCS, tree, "**", "*.md"), recursive=True):
            en_p = en_p.replace(os.sep, "/")
            if en_p.endswith("index.md"):
                continue                      # folder indexes are generated, not authored
            rel = en_p[len(DOCS.replace(os.sep, "/")) + 1:]
            ar_p = os.path.join(DOCS, "ar", rel).replace(os.sep, "/")
            if not os.path.exists(ar_p):
                continue                      # entity-flows is English-only, and that is fine
            en, ar = h1(en_p), h1(ar_p)
            if en and ar:
                pairs.add((ar, en))

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Arabic page name\tNama English name\n")
        fh.write("# Generated by tools/release-notes/gen-doc-names.py -- do not hand-edit.\n")
        for ar, en in sorted(pairs):
            fh.write(ar + "\t" + en + "\n")

    print("wrote %d name pairs to %s" % (len(pairs), os.path.relpath(OUT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
